name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Install depenqdencies
      run: yarn

    - name: Build project
      run: yarn build

    - name: (GH Pages) Route 404s, fixes Router
      run: ln -s ./src/.vuepress/dist/index.html ./src/.vuepress/dist/404.html

    - name: Publish site
      uses: KlaytonJr/JSDocs@v0.2.1
      env:
        BUILD_DIR: ./src/.vuepress/dist
